# Generated by Django 5.2 on 2025-04-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camisetas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camiseta',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='camiseta',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='camiseta',
            name='preco_normal',
        ),
        migrations.RemoveField(
            model_name='camiseta',
            name='preco_promo',
        ),
        migrations.AlterField(
            model_name='camiseta',
            name='tamanhos_disponiveis',
            field=models.JSONField(default=dict),
        ),
    ]
