# Generated by Django 5.2 on 2025-04-18 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camisetas', '0002_remove_camiseta_genero_remove_camiseta_imagem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemCamiseta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='camisetas/')),
                ('camiseta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='camisetas.camiseta')),
            ],
        ),
    ]
