# Generated by Django 5.2 on 2025-04-18 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camisetas', '0003_imagemcamiseta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camiseta',
            old_name='tamanhos_disponiveis',
            new_name='estoque',
        ),
    ]
