# Generated by Django 5.2 on 2025-04-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camisetas', '0004_rename_tamanhos_disponiveis_camiseta_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='camiseta',
            name='descricao',
            field=models.TextField(default='Descrição teste'),
        ),
    ]
