# Generated by Django 5.2 on 2025-04-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camisetas', '0007_pedido_pago_pedido_stripe_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='imagemcamiseta',
            name='imagem',
            field=models.ImageField(upload_to='camisetas/assets/'),
        ),
    ]
