# Generated by Django 5.2 on 2025-04-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camisetas', '0008_pedido_email_alter_imagemcamiseta_imagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camiseta',
            options={'ordering': ['ordem']},
        ),
        migrations.AddField(
            model_name='camiseta',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
