# Generated by Django 5.2 on 2025-04-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camisetas', '0009_alter_camiseta_options_camiseta_ordem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('enviado', 'Enviado'), ('entregue', 'Entregue')], default='pendente', max_length=20),
        ),
    ]
